#!/usr/bin/env node
/**
 * Build Script for Exquisite Corpse
 *
 * Combines separate CSS and JavaScript files into a single HTML page
 * that can be served by Cloudflare Workers.
 *
 * This solves the problem of nested template literals and makes
 * development easier by allowing proper syntax highlighting and
 * linting in separate files.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Read source files
const cssPath = path.join(rootDir, 'src', 'static', 'styles.css');
const jsPath = path.join(rootDir, 'src', 'static', 'app.js');
const htmlTemplatePath = path.join(rootDir, 'src', 'static', 'body.html');

// Output path
const outputPath = path.join(rootDir, 'src', 'pages', 'home.generated.js');

function escapeForTemplateLiteral(str) {
  // Escape backticks, dollar signs, and backslashes for use inside template literals
  return str
    .replace(/\\/g, '\\\\')    // Escape backslashes first
    .replace(/`/g, '\\`')       // Escape backticks
    .replace(/\$\{/g, '\\${');  // Escape template interpolations
}

function escapeScriptCloseTag(str) {
  // Replace </script> with a template expression that produces the same result
  // This prevents the HTML parser from seeing </script> inside our <script> block
  return str.replace(/<\/script>/gi, '</\' + \'script>');
}

async function build() {
  console.log('🔨 Building Exquisite Corpse...');

  // Read source files
  let css, js, bodyHtml;

  try {
    css = fs.readFileSync(cssPath, 'utf-8');
    console.log(`✅ Read CSS: ${css.length} bytes`);
  } catch (err) {
    console.error('❌ Failed to read CSS file:', err.message);
    process.exit(1);
  }

  try {
    js = fs.readFileSync(jsPath, 'utf-8');
    console.log(`✅ Read JS: ${js.length} bytes`);
  } catch (err) {
    console.error('❌ Failed to read JS file:', err.message);
    process.exit(1);
  }

  try {
    bodyHtml = fs.readFileSync(htmlTemplatePath, 'utf-8');
    console.log(`✅ Read HTML: ${bodyHtml.length} bytes`);
  } catch (err) {
    console.error('❌ Failed to read HTML template:', err.message);
    process.exit(1);
  }

  // Escape for embedding in template literals
  const escapedCss = escapeForTemplateLiteral(css);
  const escapedJs = escapeForTemplateLiteral(escapeScriptCloseTag(js));
  const escapedBody = escapeForTemplateLiteral(bodyHtml);

  // Generate the home.js file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by scripts/build.js from src/static/ files
// Edit the source files in src/static/ and run 'npm run build' to regenerate

export function getHomePage() {
  const css = \`${escapedCss}\`;
  const body = \`${escapedBody}\`;
  const js = \`${escapedJs}\`;

  return \`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Exquisite Corpse - Collaborative Story Game</title>
  <script src="https://cdn.tailwindcss.com"><\\/script>
  <style>\${css}</style>
</head>
<body class="p-4">
  \${body}
  <script>\${js}<\\/script>
</body>
</html>\`;
}
`;

  // Write output
  try {
    fs.writeFileSync(outputPath, output);
    console.log(`✅ Generated: ${outputPath}`);
    console.log(`📦 Total output: ${output.length} bytes`);
    console.log('🎉 Build complete!');
  } catch (err) {
    console.error('❌ Failed to write output:', err.message);
    process.exit(1);
  }
}

build();
